Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/SingleLineBlockParams:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
