require('lspkind').init({
  with_text = true,
  preset = 'codicons',
  symbol_map = {
    Text = '',
    Method = 'ƒ',
    Function = 'ƒ',
    Constructor = '',
    Variable = '',
    Class = '',
    Interface = '',
    Module = '',
    Property = '',
    Unit = '',
    Value = '',
    Enum = 'e',
    Keyword = 'k',
    Snippet = 's',
    Color = '',
    File = '',
    Folder = '',
    EnumMember = '',
    Constant = '',
    Struct = ''
  },
})
