local M = {}

M.action = "󰛩"

M.Error = ""
M.error = ""
M.Warn = ""
M.warning = ""
M.Info = ""
M.information = ""
M.Hint = ""
M.hint = ""

-- error = '  ',
-- warn = '  ',
-- info = '  ',

M.branch = ""
M.added = ""
M.modified = ""
M.removed = ""

M.Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" }
M.Breakpoint = ""
M.BreakpointCondition = ""
M.BreakpointRejected = { "", "DiagnosticError" }
M.LogPoint = ".>"

M.FolderClosed = ""
M.FolderOpen = ""
M.FolderEmpty = ""

M.Array = ""
M.Boolean = ""
M.Class = ""
M.Color = ""
M.Constant = ""
M.Constructor = ""
M.Copilot = ""
M.Enum = ""
M.EnumMember = ""
M.Event = ""
M.Field = ""
M.File = ""
M.Folder = ""
M.Function = "ƒ"
M.Interface = ""
M.Key = ""
M.Keyword = ""
M.Method = "ƒ"
M.Module = ""
M.Namespace = ""
M.Null = ""
M.Number = ""
M.Object = ""
M.Operator = ""
M.Package = ""
M.Property = ""
M.Reference = ""
M.Snippet = ""
M.String = ""
M.Struct = ""
M.Text = ""
M.TypeParameter = ""
M.Unit = ""
M.Variable = ""
M.Tag = ''
M.trace = ''
M.TabNine = "T"
M.Value = ""
M.Time = ''
M.corners = {
  round = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
  sharp = { '┌', '─', '┐', '│', '┘', '─', '└', '│' },
  double = { '╔', '═', '╗', '║', '╝', '═', '╚', '║' },
  bold = { '┏', '━', '┓', '┃', '┛', '━', '┗', '┃' },
  classic = { '╓', '─', '╖', '║', '╜', '─', '╙', '║' },
  ascii = { '+', '-', '+', '|', '+', '-', '+', '|' },
  empty = { ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ' },
  solid = { '▛', '▀', '▜', '▌', '▙', '▄', '▟', '▐' },
  dotted = { '┌', '┄', '┐', '┊', '┘', '┄', '└', '┊' },
  dashed = { '┌', '┅', '┐', '┊', '┘', '┅', '└', '┊' },
  none = { ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ' },
}

return M
-- [0] = "Root",
-- [1] = "File",
-- [2] = "Module",
-- [3] = "Namespace",
-- [4] = "Package",
-- [5] = "Class",
-- [6] = "Method",
-- [7] = "Property",
-- [8] = "Field",
-- [9] = "Constructor",
-- [10] = "Enum",
-- [11] = "Interface",
-- [12] = "Function",
-- [13] = "Variable",
-- [14] = "Constant",
-- [15] = "String",
-- [16] = "Number",
-- [17] = "Boolean",
-- [18] = "Array",
-- [19] = "Object",
-- [20] = "Key",
-- [21] = "Null",
-- [22] = "EnumMember",
-- [23] = "Struct",
-- [24] = "Event",
-- [25] = "Operator",
-- [26] = "TypeParameter",
