return {}
-- return {
--   'zbirenbaum/copilot.lua',
--   lazy = false,
--   config = function()
--     require('copilot').setup({
--       panel = {
--         enabled = true,
--         auto_refresh = true,
--         keymap = {
--           jump_prev = "<leader>k",
--           jump_next = "<leader>j",
--           accept = "<CR>",
--           refresh = "gr",
--           open = "<C-k><C-c>"
--         },
--         layout = {
--           position = "right", -- | top | left | right
--           ratio = 0.25
--         },
--       },
--       suggestion = {
--         enabled = true,
--         auto_trigger = true,
--         debounce = 75,
--         keymap = {
--           accept = "<C-c><C-o>",
--           accept_word = "<C-c><C-w>",
--           accept_line = "<C-c><C-l>",
--           next = "<C-c><C-n>",
--           prev = "<C-c><C-p>",
--           dismiss = "<C-c><C-q>",
--         },
--       },
--       filetypes = {
--         yaml = false,
--         markdown = false,
--         help = false,
--         gitcommit = false,
--         gitrebase = false,
--         hgcommit = false,
--         svn = false,
--         cvs = false,
--         ['.'] = false,
--       },
--       copilot_node_command = vim.fn.expand("$HOME") .. '/.asdf/installs/nodejs/16.17.1/bin/node', -- Node.js version must be > 16.x
--       server_opts_overrides = {},
--     })
--   end
-- }
