return {}
-- return {
--   'ray-x/lsp_signature.nvim',
--   config = function()
--     require('lsp_signature').setup({
--       bind = true,
--       doc_lines = 0,
--       hint_enable = false,
--       hint_prefix = '',
--       hint_scheme = '',
--       hi_parameter = 'LspSignatureActiveParameter',
--       max_height = 4,
--       max_width = 1000,
--       handler_opts = {
--         border = 'single'
--       },
--       -- toggle_key = '<leader>hs'
--       toggle_key = ''
--     })
--   end
-- }
