-- TODO: Check if this is still needed
return {}
-- return {
--   'Valloric/MatchTagAlways',
--   config = function()
--     vim.g.mta_filetypes = {
--       html = 1,
--       xhtml = 1,
--       xml = 1,
--       jinja = 1,
--       javascript = 1,
--       javascriptreact = 1,
--       ['javascript.jsx'] = 1,
--       typescript = 1,
--       typescriptreact = 1,
--       ['typescript.jsx'] = 1,
--       vue = 1,
--     }

--     -- vim.g.mta_use_matchparen_group       = 0
--     -- vim.g.mta_set_default_matchtag_color = 0
--   end,
-- }
